import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../../data/models/product_with_stock.dart';
import '../../auth/providers/lab_provider.dart';
import '../../inventory/providers/inventory_providers.dart';

// ── Report data model ─────────────────────────────────────

class ReportData {
  final String                  labName;
  final DateTime                generatedAt;
  final List<ProductWithStock>  allProducts;
  final List<ProductWithStock>  outOfStock;
  final List<ProductWithStock>  critical;
  final List<ProductWithStock>  reorderNeeded;
  final List<ProductWithStock>  expiringSoon;

  const ReportData({
    required this.labName,
    required this.generatedAt,
    required this.allProducts,
    required this.outOfStock,
    required this.critical,
    required this.reorderNeeded,
    required this.expiringSoon,
  });

  int get alertCount => outOfStock.length + critical.length;
}

// ── Provider ──────────────────────────────────────────────

final reportDataProvider =
    FutureProvider.autoDispose<ReportData>((ref) async {
  final lab   = ref.watch(selectedLabProvider);
  final items = await ref.watch(inventoryProvider.future);

  return ReportData(
    labName:      lab?.labName ?? 'Lab',
    generatedAt:  DateTime.now(),
    allProducts:  items,
    outOfStock:   items.where((p) => p.stockStatus == StockStatus.outOfStock).toList(),
    critical:     items.where((p) => p.stockStatus == StockStatus.critical).toList(),
    reorderNeeded: items.where((p) => p.stockStatus == StockStatus.reorder).toList(),
    expiringSoon: items.where((p) => p.hasExpiringSoon).toList(),
  );
});

// ── Plain-text report builder ─────────────────────────────

String buildReportText(ReportData data) {
  final dateFmt = DateFormat('yyyy-MM-dd HH:mm');
  final buf     = StringBuffer();

  void line([String s = '']) => buf.writeln(s);
  void section(String title) {
    line();
    line(title.toUpperCase());
    line('─' * 40);
  }

  // Header
  line('LABTRACK INVENTORY REPORT');
  line('Lab: ${data.labName}');
  line('Generated: ${dateFmt.format(data.generatedAt)}');
  line('=' * 40);

  // Summary
  section('Summary');
  line('Total products  : ${data.allProducts.length}');
  line('Out of stock    : ${data.outOfStock.length}');
  line('Critical stock  : ${data.critical.length}');
  line('Reorder needed  : ${data.reorderNeeded.length}');
  line('Expiring ≤30 d  : ${data.expiringSoon.length}');

  // Out of stock
  if (data.outOfStock.isNotEmpty) {
    section('Out of Stock');
    for (final p in data.outOfStock) {
      line('• ${p.product.name} — 0 ${p.product.unit}');
    }
  }

  // Critical
  if (data.critical.isNotEmpty) {
    section('Critical Stock');
    for (final p in data.critical) {
      line('• ${p.product.name} — ${_fmt(p.totalQuantity)} ${p.product.unit}'
          ' (min: ${_fmt(p.product.minimumStock)})');
    }
  }

  // Reorder
  if (data.reorderNeeded.isNotEmpty) {
    section('Reorder Needed');
    for (final p in data.reorderNeeded) {
      line('• ${p.product.name} — ${_fmt(p.totalQuantity)} ${p.product.unit}'
          ' (reorder at: ${_fmt(p.product.reorderPoint)})');
    }
  }

  // Expiring soon
  if (data.expiringSoon.isNotEmpty) {
    section('Expiring Soon (≤30 days)');
    for (final p in data.expiringSoon) {
      final days = p.daysUntilNextExpiry!;
      final lot  = p.fefoLot!;
      final exp  = DateFormat('yyyy-MM-dd').format(lot.expirationDate);
      line('• ${p.product.name} — ${lot.lotNumber} — expires $exp ($days days)');
    }
  }

  // Full inventory
  section('Full Inventory');
  for (final p in data.allProducts) {
    final status = switch (p.stockStatus) {
      StockStatus.ok         => '✓',
      StockStatus.reorder    => '⚠ Reorder',
      StockStatus.critical   => '⚠ Critical',
      StockStatus.outOfStock => '✗ Out of stock',
    };
    line('• ${p.product.name} — ${_fmt(p.totalQuantity)} ${p.product.unit}  $status');
  }

  line();
  line('─' * 40);
  line('Generated by LabTrack');

  return buf.toString();
}

String _fmt(double v) =>
    v == v.floorToDouble() ? v.toInt().toString() : v.toStringAsFixed(1);
